//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConfigDecryptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SIVKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SIVKey() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebConfigDecryptor.SIVKey", typeof(SIVKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8,6,7,5,3,0,9,9|1,9,9,8,2,0,0,3.
        /// </summary>
        internal static string AutoReject_SpecProBatchJob {
            get {
                return ResourceManager.GetString("AutoReject-SpecProBatchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,1,3,0,4,3,1,9|1,3,4,8,2,0,7,2.
        /// </summary>
        internal static string CBNInsertLegacyData {
            get {
                return ResourceManager.GetString("CBNInsertLegacyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,8,8,1,2,3|1,1,4,8,8,1,2,3.
        /// </summary>
        internal static string CGM {
            get {
                return ResourceManager.GetString("CGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,0,8,1,2,3,5|1,2,0,8,1,2,3,4.
        /// </summary>
        internal static string CNC {
            get {
                return ResourceManager.GetString("CNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,6,7,1,2,5|1,1,4,6,7,1,2,4.
        /// </summary>
        internal static string DCR {
            get {
                return ResourceManager.GetString("DCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,7,1,1,2,3,5|1,2,7,1,1,2,3,4.
        /// </summary>
        internal static string doa_PriceWalk {
            get {
                return ResourceManager.GetString("doa-PriceWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,9,9,8,1,2,4|1,1,9,9,8,1,2,3.
        /// </summary>
        internal static string Envis {
            get {
                return ResourceManager.GetString("Envis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,1,3,0,4,3,1,9|1,3,4,8,2,0,7,2.
        /// </summary>
        internal static string EventViewer {
            get {
                return ResourceManager.GetString("EventViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,1,5,1,8,1,2,4|2,1,5,1,8,1,2,3.
        /// </summary>
        internal static string ITCOCorp {
            get {
                return ResourceManager.GetString("ITCOCorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,1,5,1,8,1,2,4|2,1,5,1,8,1,2,3.
        /// </summary>
        internal static string ITCOEngineer {
            get {
                return ResourceManager.GetString("ITCOEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,7,3,4,0,1,2,4|2,7,3,4,0,1,2,3.
        /// </summary>
        internal static string OrderExplorer {
            get {
                return ResourceManager.GetString("OrderExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,7,2,4,7,1,2,4|2,7,2,4,7,1,2,3.
        /// </summary>
        internal static string PQR {
            get {
                return ResourceManager.GetString("PQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8,6,7,5,3,0,9,9|1,9,9,8,2,0,0,3.
        /// </summary>
        internal static string PWL {
            get {
                return ResourceManager.GetString("PWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8,6,7,5,3,0,9,9|1,9,9,8,2,0,0,3.
        /// </summary>
        internal static string PWMS {
            get {
                return ResourceManager.GetString("PWMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,7,3,6,9,1,2,5|2,7,3,6,9,1,2,4.
        /// </summary>
        internal static string SalesCampaignTool {
            get {
                return ResourceManager.GetString("SalesCampaignTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,1,0,1,2,3,5|1,2,1,0,1,2,3,4.
        /// </summary>
        internal static string SCO {
            get {
                return ResourceManager.GetString("SCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,7,2,4,7,1,2,4|2,7,2,4,7,1,2,3.
        /// </summary>
        internal static string SOLive {
            get {
                return ResourceManager.GetString("SOLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,1,3,0,4,3,1,9|1,3,4,8,2,0,7,2.
        /// </summary>
        internal static string SP21DB2Parser {
            get {
                return ResourceManager.GetString("SP21DB2Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,1,3,0,4,3,1,9|1,3,4,8,2,0,7,2.
        /// </summary>
        internal static string SpecPro {
            get {
                return ResourceManager.GetString("SpecPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,6,5,1,2,5|1,1,4,6,5,1,2,4.
        /// </summary>
        internal static string SPOE {
            get {
                return ResourceManager.GetString("SPOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,8,0,1,2,4|1,1,4,8,0,1,2,3.
        /// </summary>
        internal static string WAA_AutoApprovalBatchJob {
            get {
                return ResourceManager.GetString("WAA-AutoApprovalBatchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,8,0,1,2,4|1,1,4,8,0,1,2,3.
        /// </summary>
        internal static string WAA_Corporate {
            get {
                return ResourceManager.GetString("WAA-Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,4,8,0,1,2,4|1,1,4,8,0,1,2,3.
        /// </summary>
        internal static string WAA_Supplier {
            get {
                return ResourceManager.GetString("WAA-Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,1,3,0,4,3,1,9|1,3,4,8,2,0,7,2.
        /// </summary>
        internal static string WebTCO {
            get {
                return ResourceManager.GetString("WebTCO", resourceCulture);
            }
        }
    }
}
